<?php echo $this->getFilterType();?>
<ol xmlns="http://www.w3.org/1999/html">
    <?php foreach ($this->getItems() as $_item): ?>
        <?php if ($_item->getCount() > 0): ?>
            <input type="checkbox" value="<?php echo $this->urlEscape($_item->getUrl()) ?>"
                   onClick="if (this.checked) { window.location = this.value; }"/>
            <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?>
                <?php if ($this->shouldDisplayProductCount()): ?>
                    <span class="count">(<?php echo $_item->getCount() ?>)</span>
                <?php endif; ?>
            </a>
        <?php else: ?>
            <span>
                <?php echo $_item->getLabel(); ?>
                <?php if ($this->shouldDisplayProductCount()): ?>
                    <span class="count">(<?php echo $_item->getCount() ?>)</span>
                <?php endif; ?>
            </span>
        <?php endif; ?>
            <br>
    <?php endforeach ?>
</ol>
