<style>
    .select-style {
        border: 1px solid #ccc;
        width: 100%;
        height: 28px;
        overflow: hidden;
        background: no-repeat right #FEFEFE;
        -webkit-border-radius: 3px;
        border-radius: 3px;
        -webkit-box-shadow: inset 0px 0px 10px 1px #FEFEFE;
        box-shadow: inset 0px 0px 10px 1px #FEFEFE;
    }
    .select-style select {
        background: transparent;
        width: 170px;
        font-size:7pt;
        color:grey;
        border: 0;
        border-radius: 0;
        height: 28px;
        -webkit-appearance: none;
    }
    .select-style select:focus {
        outline: none;
    }

</style>
<?php echo $this->getFilterType(); ?>
<ol>
    <select class="select-style" onclick="this.options[this.selectedIndex].value && (window.location = this.options[this.selectedIndex].value);">
        <option value="">Please Select</option>
        <?php foreach ($this->getItems() as $_item): ?>
            <?php if ($_item->getCount() > 0): ?>
                <option value="<?php echo $this->urlEscape($_item->getUrl()) ?>">
                <?php echo $_item->getLabel() ?>
                <?php if ($this->shouldDisplayProductCount()): ?>
                    <span class="count">(<?php echo $_item->getCount() ?>)</span>
                <?php endif; ?>
            <?php else: ?>
                <span>
                <?php echo $_item->getLabel(); ?>
                    <?php if ($this->shouldDisplayProductCount()): ?>
                        <span class="count">(<?php echo $_item->getCount() ?>)</span>
                    <?php endif; ?>
                </span>
                </option>
            <?php endif; ?>
        <?php endforeach ?>
    </select>
</ol>
