<?php if (Mage::getStoreConfig('general/hungbd_bestseller/enableoncate')): ?>
    <?php $productPerView = (int)Mage::getStoreConfig('general/hungbd_bestseller/slider_per_view_category'); ?>
    <?php $products = $this->getBestSellerProductCategory()  ?>
    <?php $customProducts = $this->getCustomBestSellerCategory()  ?>

    <?php if ($products || $customProducts): ?>
        <style>
            .best-seller {
                width: 100%;
                height: 100%;
            }
            .best-seller {
                text-align: center;
                font-size: 18px;
                background: #fff;
                /* Center slide text vertically */
                display: -webkit-box;
                display: -ms-flexbox;
                display: -webkit-flex;
                display: flex;
                -webkit-box-pack: center;
                -ms-flex-pack: center;
                -webkit-justify-content: center;
                justify-content: center;
                -webkit-box-align: center;
                -ms-flex-align: center;
                -webkit-align-items: center;
                align-items: center;
            }

            .best-seller img {
                width: 110px;
                height: 110px;
            }
        </style>
        <?php if ($customProducts || $product ): ?>
        <h3 align="center">Best Seller Product</h3>
        <div class="swiper-container best-seller">
            <div class="swiper-wrapper">
                <?php foreach ($customProducts->getItems() as $product): ; ?>
                    <div class="swiper-slide">
                        <a href="<?php echo $product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($product->getName(), null, true) ?>"
                           class="product-image">
                            <img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(110, 110) ?>"
                            />
                        </a>
                        <div class="product-info">
                            <h3 class="product-name"><a href="<?php echo $product->getProductUrl() ?>"
                                                        title="<?php echo $this->stripTags($product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($product, $product->getName(), 'name') ?></a>
                            </h3>
                            <?php echo $this->getPriceHtml($product, true, '-widget-new-grid') ?>
                        </div>
                    </div>
                <?php endforeach; ?>
                <?php foreach ($products->getItems() as $product): ; ?>
                    <div class="swiper-slide">
                        <a href="<?php echo $product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($product->getName(), null, true) ?>"
                           class="product-image">
                            <img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(110, 110) ?>"
                            />
                        </a>
                        <div class="product-info">
                            <h3 class="product-name"><a href="<?php echo $product->getProductUrl() ?>"
                                                        title="<?php echo $this->stripTags($product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($product, $product->getName(), 'name') ?></a>
                            </h3>
                            <?php echo $this->getPriceHtml($product, true, '-widget-new-grid') ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="swiper-pagination hungbd-best-pag"></div>
        </div>
    <?php endif; ?>
    <script>
            var swiper = new Swiper('.best-seller', {
                slidesPerView: <?php echo $productPerView; ?> ,
                spaceBetween: 10,
                centeredSlides: true,
                autoplay: {
                    delay: 5000,
                },
                <?php if (count($products->getItems()) >= $productPerView): ?>
                loop: true,
                <?php endif; ?>

                mousewheel: {
                    invert: true,
                },
            });
        </script>
    <?php endif; ?>
<?php endif; ?>