<?php
$active = true;
if (Mage::getStoreConfig('mybestseller/bestseller_group/active') === 0) {
    $active = false;
}
if ($active) {
    ?>
    <style>
        .product-slide {
            height     : auto;
            text-align : center;
        }
    </style>
    <div class="widget widget-new-products">
        <div class="widget-title"><h2>Bestseller Products</h2></div>
        <div class="swiper-container product-slide">
            <div class="swiper-wrapper">
                <?php
                $products = $this->getProducts();
                foreach ($products as $item) {
                    ?>
                    <div class="swiper-slide">
                        <a href="<?php echo $item->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($item->getName(), null, true) ?>" class="product-image">
                            <img src="<?php echo $this->helper('catalog/image')->init($item, 'small_image')->resize(210) ?>"
                                 alt="<?php echo $this->stripTags($item->getName(), null, true) ?>"/>
                        </a>
                        <div class="product-info">
                            <h3 class="product-name">
                                <a href="<?= $item->getProductUrl() ?>"
                                   title="<?= $this->stripTags($item->getName(), null, true) ?>">
                                    <?= $this->helper('catalog/output')->productAttribute($item, $item->getName(), 'name') ?>
                                </a>
                            </h3>
                            <?php echo $this->getPriceHtml($item, true, '-widget-new-grid') ?>
                            <?php echo $this->getReviewsSummaryHtml($item, 'short') ?>
                            <div class="actions">
                                <?php if ($item->isSaleable()): ?>
                                    <button type="button"
                                            title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>"
                                            class="button btn-cart"
                                            onclick="setLocation('<?php echo $this->getAddToCartUrl($item) ?>')">
                                        <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <?php else: ?>
                                    <p class="availability out-of-stock">
                                        <span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->getAddToWishlistUrl($item) ?>"
                                               class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if ($_compareUrl = $this->getAddToCompareUrl($item)): ?>
                                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>"
                                                                                class="link-compare"><?php echo $this->__('Add to Compare') ?></a>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>
            <div class="swiper-pagination"></div>
            <div class="swiper-scrollbar"></div>
        </div>
    </div>

    <script>
        <?php
        $qty = 5;
        $effect = '';
        if (!empty(Mage::getStoreConfig('mybestseller/bestseller_group/qty'))) {
            $qty = Mage::getStoreConfig('mybestseller/bestseller_group/qty');
        }
        if (!empty(Mage::getStoreConfig('mybestseller/bestseller_group/effect'))) {
            $effect = Mage::getStoreConfig('mybestseller/bestseller_group/effect');
        }
        ?>
        var bestseller = new Swiper('.product-slide', {
            slidesPerView: <?= $qty ?>,
            effect: '<?= $effect ?>',
            spaceBetween: 30,
            autoplay: {
                delay: 5000,
            },
            loop: true,
            pagination: {
                el: '.swiper-pagination',
                clickable: true
            }
        });
    </script>
    <?php
}
