<?php
$yes = Mage::getStoreConfig('smslider/sm_slider/enable');
if ($yes) {
    $sliderConfig = Mage::getStoreConfig('smslider/sm_slider/slider_chose');
    $listImage = Mage::getModel('sm_slider/listimage')
        ->getCollection()
        ->join(array('image' => 'sm_slider/image'),
            'main_table.image_id=image.id',
            array('name', 'link', 'text'))
        ->addFilter('slider_id', $sliderConfig);

    ?>
    <?php $sliderType = Mage::getStoreConfig('smslider/sm_slider/slider_type'); ?>
    <style>
        .swiper-container {
            width: 100%;
            height: 530px;

        }

        .swiper-container div {
            width: 100%;



        }

        .swiper-container div img {
            width: 100%;
            height: 85%;

        }

        .center-bottom {
            position: absolute;
            bottom: 26px;
            color: #751d02;
            font-size: 30px;
            font-style: inherit;
        }

        .size_img {

        }

    </style>
    <div class="swiper-container">
        <!-- Additional required wrapper -->
        <div class="swiper-wrapper">
            <!-- Slides -->
            <?php  foreach ($listImage as $item): ?>
                <?php $lefttab = 55 - strlen($item->text); ?>
                <div class="swiper-slide"><img src="<?php echo $item->link; ?>">
                    <div class="center-bottom"<?php if ($lefttab > 0){ ?> style="left: <?php echo $lefttab; ?>%">
                        <marquee class="nhapnhay" direction="down" scrollamount="2"><?php echo $item->text; ?></marquee>
                        <?php } else { ?>
                            ><marquee class="nhapnhay" scrollamount="10"><?php echo $item->text; ?></marquee>
                        <?php } ?>
                    </div>
                </div>
            <?php endforeach;?>
        </div>
        <!-- If we need pagination -->

        <div class="swiper-pagination"></div>
        <!-- If we need scrollbar -->
        <div class="swiper-scrollbar"></div>
    </div>
<?php } else {
} ?>
<script>
    var swiper = new Swiper('.swiper-container', {
        direction: '<?php echo $sliderType; ?>',
        autoplay: {
            delay: 6000,
        },
        loop: true,
        spaceBetween: 20,
        slidesPerView: 1,
        pagination: {
            el: '.swiper-pagination',
            type: 'bullets',
            clickable: true,
        },
        mousewheel: {
            invert: true,
        },
    });
</script>