<?php
//var_dump($this->getProducts());die;
$active = true;
if (Mage::getStoreConfig('mybestseller/bestseller_group/active') === 0) {
    $active = false;
}
if ($active) {
    ?>
    <style>
        .product-slide {
            height     : auto;
            text-align : center;
        }
        .swiper-slide > a > img {
            width: 100%;
        }
    </style>
    <div class="widget widget-new-products">
        <div class="widget-title"><h2>Bestseller Products</h2></div>
        <div class="swiper-container product-slide">
            <div class="swiper-wrapper">
                <?php
                $products = $this->getProducts();
                foreach ($products as $item) {
                    ?>
                    <div class="swiper-slide">
                        <a href="<?php echo $item->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($item->getName(), null, true) ?>"
                           class="product-image prd-link">
                            <?php $label = $item->getProduct_label(); ?>
                            <?php if(strpos($label, 'new') !== false) {?>
                                <div class="mylabel new-prd">
                                    <div class="new-label">New</div>
                                </div>
                            <?php } ?>
                            <?php if(strpos($label, 'sale') !== false) {?>
                                <div class="mylabel sale-prd">
                                    <div class="sale-label">Sale</div>
                                </div>
                            <?php } ?>
                            <?php if(strpos($label, 'promotion') !== false) {?>
                                <div class="promotion-label">Promotion</div>
                            <?php } ?>
                            <img src="<?php echo $this->helper('catalog/image')->init($item, 'small_image')->resize(210) ?>"
                                 alt="<?php echo $this->stripTags($item->getName(), null, true) ?>"/>
                        </a>
                        <div class="product-info">
                            <h3 class="product-name">
                                <a href="<?= $item->getProductUrl() ?>"
                                   title="<?= $this->stripTags($item->getName(), null, true) ?>">
                                    <?= $this->helper('catalog/output')->productAttribute($item, $item->getName(), 'name') ?>
                                </a>
                            </h3>
                            <?php echo $this->getPriceHtml($item, true, '-widget-new-grid') ?>
                            <?php echo $this->getReviewsSummaryHtml($item, 'short') ?>
                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>
            <div class="swiper-pagination"></div>
            <div class="swiper-scrollbar"></div>
        </div>
    </div>
    <script>
        <?php
        $qty = 5;
        $effect = '';
        if (!empty(Mage::getStoreConfig('mybestseller/bestseller_group/qty'))) {
            $qty = Mage::getStoreConfig('mybestseller/bestseller_group/qty');
        }

        if (!empty(Mage::getStoreConfig('mybestseller/bestseller_group/effect'))) {
            $effect = Mage::getStoreConfig('mybestseller/bestseller_group/effect');
        }
        ?>
        var bestseller = new Swiper('.product-slide', {
            slidesPerView: <?= $qty ?>,
            effect: '<?= $effect ?>',
            spaceBetween: 20,
            mousewheel: true,
            autoplay: {
                delay: 5000,
            },
            loop: false,
            pagination: {
                el: '.swiper-pagination',
                clickable: true
            }
        });

    </script>
    <?php
}
