<?php
if (Mage::getStoreConfig('myslider/slider_group/active') == 0) {
    ?>
    <div class="slideshow-container">
        <ul class="slideshow">
            <li>
                <a href="<?php echo Mage::getUrl('accessories/eyewear.html') ?>">
                    <img src="<?php echo Mage::getBaseUrl('media') . 'wysiwyg/slide-1.jpg' ?>"
                         alt="An eye for detail - Click to Shop Eye Wear"/></a>
            </li>
            <li>
                <a href="<?php echo Mage::getUrl('women.html') ?>">
                    <img src="<?php echo Mage::getBaseUrl('media') . 'wysiwyg/slide-2.jpg' ?>"
                         alt="Style solutions - covet-worthy styles in travel-friendly fabrics - Click to Shop Woman"/>
                </a>
            </li>
            <li>
                <a href="<?php echo Mage::getUrl('men.html') ?>">
                    <img src="<?php echo Mage::getBaseUrl('media') . 'wysiwyg/slide-3.jpg' ?>"
                         alt="Wing man - hit the runway in stylish separates and casuals - Click to Shop Man"/>
                </a>
            </li>
        </ul>
        <div class="slideshow-pager">&nbsp;</div>
        <span class="slideshow-prev">&nbsp;</span>
        <span class="slideshow-next">&nbsp;</span>
    </div>
    <?php
} else {
    ?>

    <style>
        .swiper-container {
            width  : 100%;
            height : 500px;
        }

        .swiper-slide {
            height              : inherit;
            font-size           : 18px;
            background          : #fff;
            background-repeat   : no-repeat;
            background-size     : cover;
            background-position : center;
        }

        .swiper-slide > a {
            display         : block;
            height          : 100%;
            width           : 100%;
            text-decoration : none;
        }

        a:hover {
            cursor : pointer;
        }

        .text {
            max-width : 40%;
            width     : intrinsic;
            width     : -moz-max-content;
            width     : -webkit-max-content;
            height    : 100%;
            font-size : 1.5em;
            padding   : 50px;
            color     : #fff;
        }

        .text > p {
            background : rgba(7, 65, 47, 0.3);
        }

        .gallery-top {
            height : 80%;
            width  : 100%;
        }

        .gallery-thumbs {
            height     : 20%;
            box-sizing : border-box;
            padding    : 10px 0;
        }

        .gallery-thumbs .swiper-slide {
            width   : 25%;
            height  : 100%;
            opacity : 0.4;
        }

        .gallery-thumbs .swiper-slide-active {
            opacity : 1;
        }
    </style>
    <div class="swiper-container parent-slide">
    <div class="swiper-wrapper">
    <?php
    $images = $this->getData('list');
    foreach ($images as $item) {
    ?>
    <?php $urlImage = Mage::getBaseUrl('media') . 'dangnd/slide/' . $item['name']; ?>
    <div class="swiper-slide" style="background-image:url(<?php echo $urlImage ?>)">
        <?php if(!empty($item['link'])) { ?>
        <a href="<?php echo ($item['link']) ? $item['link'] : '#' ?>"><?php } ?>
            <div class="text">
                <p><?php echo $item['content'] ?></p>
            </div>
        <?php if(!empty($item['link'])) {
            echo '</a>';
        } ?>
    </div>
    <?php
    }
    ?>
    </div>
    <div class="swiper-pagination"></div>
    <div class="swiper-scrollbar"></div>
    </div>

    <script>
        var swiper = new Swiper('.parent-slide', {
            direction: '<?php echo Mage::getStoreConfig('myslider/slider_group/type') ?>',
            spaceBetween: 30,
            mousewheel: true,
            autoplay: {
                delay: 3000,
            },
            pagination: {
                el: '.swiper-pagination',
                clickable: true
            }
        });
    </script>
    <?php
}
