<?php if (($_products = $this->getFeaturedProduct())): ?>
    <div class="widget widget-new-products">
        <div class="widget-title">
            <h2><?php echo 'Featured Products'; ?></h2>
        </div>
        <div class="widget-products">
            <?php $_columnCount = 5; ?>
            <?php $i=0; ?>
            <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col-widget">
                <?php foreach ($_products->getItems() as $_product): ?>
                    <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                        <?php $_imgSize = 210; ?>
                        <?php // The image size is locked at 210 for this for display purposes. CSS has it at 75% which should equate to 278px?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(210) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
                        </a>
                        <div class="product-info">
                            <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                            <?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
