<?php $firstMenuItem = Mage::getModel('tungtt_megamenu/menuitem')->getCollection()->addFilter('level', '0'); ?>
<?php $maxLevel = (int)Mage::getStoreConfig('general/tungtt_megamenu/level'); ?>
<?php $listMenuItem = Mage::getModel('tungtt_megamenu/menuitem')->getCollection(); ?>
<?php $nav = 'nav';
$count = 0; ?>
<nav id="nav">
<div id="mainn" class="main" style="position:relative">
    <div class="container-fluid menu-bg" style="width: 100%;">
        <div class="row-fluid site-width bm-container">
            <div class="top-nav">
                <ul>
                    <?php foreach ($firstMenuItem as $key => $item): ?>
                        <?php $newnav = $nav . '-' . $count;
                        $count++; ?>
                        <li class="level0 <?php echo $newnav; ?>">
                            <a href="<?php echo $item->link; ?>" class="level0"><?php echo $item->name; ?></a>
                            <?php $this->getChildItem($item, $maxLevel, $listMenuItem); ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>
</nav>