<?php
/**
 * Created by PhpStorm.
 * User: nddang196
 * Date: 21-10-2017
 * Time: 08:29 SA
 */

class Datdt_Megamenu_Block_Adminhtml_Category_Edit_Form extends Mage_Adminhtml_Block_Widget_Form
{
    public function __construct()
    {
        parent::__construct();

        $this->setId('editCategory');
        $this->setTitle(Mage::helper('datdt_category')->__('Category Information'));
    }

    public function _prepareForm()
    {
        $model = Mage::registry('categoryModel');

        $form = new Varien_Data_Form(array(
            'id'     => 'edit_form',
            'action' => $this->getData('action'),
            'method' => 'post',
            'enctype' => 'multipart/form-data'
        ));

        $fieldset = $form->addFieldset('base', array(
            'ledend' => Mage::helper('datdt_category')->__('Menu Information')
        ));

        $fieldset->addType('image', 'Datdt_MegaMenu_Block_Adminhtml_Category_Helper_Category');

        $fieldset->addField('name', 'text', array(
            'name'     => 'name',
            'label'    => Mage::helper('datdt_category')->__('Name'),
            'class'    => 'required-entry',
            'required' => true
        ));
        $fieldset->addField('link', 'text', array(
            'name'     => 'text[]',
            'label'    => Mage::helper('datdt_category')->__('Link'),
            'multiple' => 'multiple',
            'class'    => 'required-entry',
            'required' => true
        ));

        if ($model->getId())
        {
            $fieldset->addField('id', 'hidden', array(
                'name' => 'id',
            ));
        }

        $form->addValues($model->getData());
        $form->setUseContainer(true);
        $form->setAction($this->getUrl('*/album/save'));

        $this->setForm($form);

        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
}